name: Raw Thoughts CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "npm"

      # install dependencies
      - run: npm ci
      # run ESLint & Prettier
      # - run: npm run lint
      # - run: npm run prettier
      # # verify that there are no build errors
      # - run: npm run build
      # # run tests with Cypress
      # - name: Cypress run
      #   uses: cypress-io/github-action@v2
      #   with:
      #     start: npm start
